#ifndef DBACCESSLAYER_GLOBAL_H
#define DBACCESSLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DBACCESSLAYER_LIB
# define DBACCESSLAYER_EXPORT Q_DECL_EXPORT
#else
# define DBACCESSLAYER_EXPORT Q_DECL_IMPORT
#endif

#endif // DBACCESSLAYER_GLOBAL_H
